export const pngs = {
  buyAndSell: "/png/Buy&Sell.png",
  availableProperty1: "/png/availableProperty1.png",
  availableProperty2: "/png/availableProperty2.png",
  availableProperty3: "/png/availableProperty3.png",
  houseForRent: "/png/HousesforRent.png",
  houseForSale: "/png/HousesforSale.png",
  investmentPlans: "/png/InvestmentPlans.png",
  jennyWilson: "/png/JennyWilson.png",
  overseasClients: "/png/OverseasClients.png",
  plopForSale: "/png/PlotForSale.png",
  robertMartin: "/png/RobertMartin.png",
  vector: "/png/vector2.png",
  group: "/png/Group.png",
  AboutUs_img: "/png/about_img.png",
  bgTools: "/png.bgTools.png",
  sixthCard: "/png/bgSixthCard.png",
  renovation: "/png/bgRenovation.png",
  infrastructure: "/png/bgInfrastructure.png",
  commercial: "/png/bgCommercial.png",
  tools: "/png/bgTools.png",
  property1: "/png/property1.png",
  property2: "/png/property2.png",
  property3: "/png/property3.png",
  Circle: "/png/circle.png",
  servicesBgImg: "/png/servicesBgImg.png",
  Residential1: "/png/Residential1.png  ",
  Residential2: "/png/Residential2.png",
  Residential3: "/png/Residential3.png",
  Residential4: "/png/Residential4.png",
  Residential5: "/png/Residential5.png",
  Residential6: "/png/Residential6.png",
  construction: "/png/bgConstruction.png",
  kitchen: "/png/bgKitcen.png",
  heart: "/png/heart.png",
  plus: "/png/plus-icon.png",
};

export const svgs = {
  builders: "/svg/builders.svg",
  buildersWhite: "/svg/buildersWhite.svg",
  goldenStar: "/svg/GoldenStar.svg",
  hamburgerBlack: "/svg/hamburgerBlack.svg",
  hamburgerWhite: "/svg/hamburgerWhite.svg",
  rightArrow: "/svg/RightArrow.svg",
  LeftArrow: "/svg/LeftArrow.svg",
  silverStar: "/svg/SilverStar.svg",
  phone: "/svg/phone.svg",
  message: "/svg/message.svg",
  location: "/svg/location.svg",
  adress: " /svg/adress-logo.svg",
  emailIcon: "/svg/email-icon.svg",
  telIcon: "/svg/Tel-icon.svg",
  instagram: "/svg/instagram-icon.svg",
  twitter: "/svg/twitter icon.svg",
  facebook: "/svg/fb-icon.svg",
  couple: "/svg/men-women.svg",
  homeFront: "/svg/home-front.svg",
  blog_2: "/svg/blog-2.svg",
  blog_3: "/svg/blog-3.svg",
  couple2: "/svg/Couple.svg",
  residentialCase: "/svg/residential-image.svg",
  residentBuilding: "/svg/resident-building.svg",
  commercial: "/svg/commercial-icon.svg",
  infrastructure: "/svg/infrastructure-icon.svg",
  tools: "/svg/Tools-icon.svg",
  renovation: "/svg/renovation-icon.svg",
  sixthCard: "/svg/sixthcard-icon.svg",
  servicesArrow: "/svg/servicesArrow.svg",
  Search: "/svg/search.svg",
  Cross: "/svg/cross.svg",
  YArrows: "/svg/2YArrows.svg",
  HeartBorder: "/svg/HeartBorder.svg",
  bed: "/svg/bed.svg",
  arrowDiagnol: "/svg/arrowDiagnol.svg",
  bathTub: "/svg/bathTub.svg",
  Heart: "/svg/Heart.svg",
  handSign: "/svg/handsign-icon.svg",
  circleHome: "/svg/home-circle-icon.svg",
  threeHome: "/svg/three-home-icon.svg",
  cross: "/svg/cross-icon.svg",
  house: "/svg/big-house.svg",
  room: "/svg/sofa-room.svg",
  doubleArrow: "/svg/double-sided-arrow-icon.svg",
  bed: "/svg/bed-icon.svg",
  bathTub: "/svg/bath-tub-icon.svg",
  goldenSquare: "/svg/golden-sqaure.svg",
  kitchen: "/svg/kitchen.svg",




};
