export const pngs = {
  buyAndSell: "/png/Buy&Sell.png",
  availableProperty1: "/png/availableProperty1.png",
  availableProperty2: "/png/availableProperty2.png",
  availableProperty3: "/png/availableProperty3.png",
  houseForRent: "/png/HousesforRent.png",
  houseForSale: "/png/HousesforSale.png",
  investmentPlans: "/png/InvestmentPlans.png",
  jennyWilson: "/png/JennyWilson.png",
  overseasClients: "/png/OverseasClients.png",
  plopForSale: "/png/PlotForSale.png",
  robertMartin: "/png/RobertMartin.png",
  vector: "/png/vector2.png",
  group: "/png/Group.png",
  AboutUs_img: "/png/about_img.png",
};

export const svgs = {
  builders: "/svg/builders.svg",
  buildersWhite: "/svg/buildersWhite.svg",
  goldenStar: "/svg/GoldenStar.svg",
  hamburgerBlack: "/svg/hamburgerBlack.svg",
  hamburgerWhite: "/svg/hamburgerWhite.svg",
  rightArrow: "/svg/RightArrow.svg",
  LeftArrow: "/svg/LeftArrow.svg",
  silverStar: "/svg/SilverStar.svg",
  phone: "/svg/phone.svg",
  message: "/svg/message.svg",
  location: "/svg/location.svg",
  adress: " /svg/adress-logo.svg",
  emailIcon: "/svg/email-icon.svg",
  telIcon: "/svg/Tel-icon.svg",
  instagram: "/svg/instagram-icon.svg",
  twitter: "/svg/twitter icon.svg",
  facebook: "/svg/fb-icon.svg",
  couple: "/svg/men-women.svg",
  homeFront: "/svg/home-front.svg",

};
